{% set name = "quest" %}
{% set version = "3.0.0" %}
{% set sha256 = "b31b5483777db318ab9a92e3825c245305582c4f9c7ad5c2308bba4c38728062" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/09/37/879ba1653bee01d44bf606ed578d3db2332d72aa79d359aa6cad64a51435/erdc_quest-3.0.0.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host: 
    - python >=3
    - pip
    - pbr
    - pytest-runner

  run:
    - python >=3
    - pbr
    - pytest
    - click
    - distributed >=1.18
    - fiona
    - gdal
    - geojson
    - libgdal
    - peewee
    - pandas <=0.22.0
    - geopandas
    - jinja2
    - matplotlib
    - numpy
    - param >=1.8.1
    - pint
    - pony
    - psutil
    - pyyaml
    - rasterio
    - sortedcollections
    - tornado
    - ulmo >=0.8.3.2
    - werkzeug
    
test:
  imports:
    - quest
    - quest_provider_plugins
    - quest_io_plugins
    - quest_tool_plugins
    - quest.tools

about:
  home: https://github.com/erdc/quest
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'https://github.com/erdc/quest'
  description: |
    Quest is a Python library that provides the ability to search, publish and 
    download data (both geographical and non-geographical) from multiple data 
    sources, including local repositories and web-based data providers. Quest 
    also provides a suite of tools for manipulating and transforming data once 
    it is downloaded.
  doc_url: https://quest.readthedocs.io/
  dev_url: https://github.com/erdc/quest

extra:
  recipe-maintainers:
    - AaronV77
    - sdc50
    - dharhas
