{% set name = "quest" %}
{% set version = "3.0.1" %}
{% set sha256 = "1ffdc66c6c08b1310607fab5da0bab7680b2ee78d42b0f93c3848a26307e3c68" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/ab/25/c545b465e082eef90a3bfd1442edaf38042b9ee2453730073893f0746ddf/erdc-quest-3.0.1.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host: 
    - python >=3
    - pip
    - pbr

  run:
    - python >=3
    - pbr
    - cartopy
    - distributed >=1.18
    - geojson
    - girder-client
    - hs_restclient
    - imageio
    - pandas <=0.22.0
    - geopandas
    - numpy
    - param >=1.8.1
    - pint
    - pony
    - psutil
    - pyyaml
    - rasterio
    - tornado
    - ulmo >=0.8.3.2
    - whitebox_tools
    - xarray

test:
  imports:
    - quest
    - quest_provider_plugins
    - quest_io_plugins
    - quest_tool_plugins
    - quest.tools

about:
  home: https://github.com/erdc/quest
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'https://github.com/erdc/quest'
  description: |
    Quest is a Python library that provides the ability to search, publish and 
    download data (both geographical and non-geographical) from multiple data 
    sources, including local repositories and web-based data providers. Quest 
    also provides a suite of tools for manipulating and transforming data once 
    it is downloaded.
  doc_url: https://quest.readthedocs.io/
  dev_url: https://github.com/erdc/quest

extra:
  recipe-maintainers:
    - AaronV77
    - sdc50
    - dharhas
