travis:
  secure:
    BINSTAR_TOKEN: wYzeL04R+3qgJIWg84C2lxiZ230io6fWGRDifV81wbqt/CjhAZjT7gRPthM7n2RVKYS+keS+W62jVdk0QYa18SPyl6aFqJQ9jVqwsPLyajeSPLyz6FcA6197nHwDa2JRRhbu2A0J2VNSBdRAA8M/P6uFatgXx0U0D4FNJabIOgKR/N6JXwryqDO48lgAuzBOrrdMjrFTcOQYQJCs+qQOrLejSHdjF8nvlAB7Yz4tbCVTvMfpyPyPsz44BdXj5D+RZLV4zSU4HnvBp9dFxd4140CRbvWxBdVT00UxdKVFZTjSZnU6NGFMCmf0ZDfD4IkCxTZ3/K2IEYtY92eZCrpgZDwFuQPyPyol0BJPJOr5Lou9diRnUWz9qj5CqpVacqk83pzSr/9MpVNMW7LhgyMY2ByndYG+wSo/ltofoId+tiIOHb5ah0LqpVWdCUEaT2Bsxo1OJEjuSb/taGR5Wnb1iCEAXkbjdL/3xkMiG9gYpPbmM/SeVN9lkU6Hxv+4x9CDREZLI/bqLL0ULXpUSjC29CwPj8KXGPq/IR1rLqS2U1BkrLMRu+PS8196p7A6JNPMOV5Xhu3gY5hWOhugjKYurvGsNltAveCo7fT29Ojh6iG8wWBOpn3p+dAZKLirU0bsNTnIkV53DXeyETJIor73KVUyAbHghT2D4q+T4ZGE3Ug=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
